### ISSUE TITLE
Incompatibility with ruby 2.2

### ISSUE THREAD

**Issue by anatol** [ruby-gnome2/pkg-config#11]
I am trying to build subtle project with 2.2 and it fails to compile because some headers are not found. I started digging into the problem and found that pkg-config 1.1.6 behaves differently with 2.1.5 and 2.2.0 ruby versions.

Here is output on Linux Arch:

ruby 2.2.0

```
irb(main):002:0> require 'pkg-config'
=> true
irb(main):003:0> pkg_config("xft")
=> ["", "", "-lXft"]
```

ruby 2.1.5

```
irb(main):001:0> require 'pkg-config'
=> true
irb(main):002:0> pkg_config("xft")
=> ["-I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz", "", "-lXft"]
```

As you see on ruby 2.2.0 it does not return cflags data.

Here is `/usr/lib/pkgconfig/xft.pc` from my system

```
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: Xft
Description: X FreeType library
Version: 2.3.2
Requires: xproto
Requires.private: xrender, fontconfig, freetype2
Cflags: -I${includedir}
Libs: -L${libdir} -lXft
```

**Comment by kou** [comment]
Oh. I missed this.
Yes. `#pkg_config` is a method from mkmf.rb.
