### ISSUE TITLE
`gem install cairo` on OpenBSD fails: `parse_pc': .pc for pixman-1 doesn't exist.

### ISSUE THREAD

**Issue by clintpachl** [ruby-gnome2/pkg-config#15]
Installing the cairo gem fails because pkg-config cannot find *pixman-1* on my OpenBSD 6.1-release system. The X11 pkgconfig in OpenBSD is under /usr/X11R6/, not /usr/X11/ like many UNIX systems.

    $ locate '*/pkgconfig'
    /usr/X11R6/lib/pkgconfig
    /usr/lib/pkgconfig
    /usr/local/lib/pkgconfig
    /usr/local/share/pkgconfig

    $ locate pixman
    /usr/X11R6/include/pixman-1
    /usr/X11R6/include/pixman-1/pixman-version.h
    /usr/X11R6/include/pixman-1/pixman.h
    /usr/X11R6/lib/libpixman-1.a
    /usr/X11R6/lib/libpixman-1.la
    /usr/X11R6/lib/libpixman-1.so.32.6
    /usr/X11R6/lib/pkgconfig/pixman-1.pc

The work around was:

    $ PKG_CONFIG_LIBDIR=/usr/X11R6/lib/pkgconfig/ gem install cairo

But I think the `default_paths` array could be fixed:

    --- /home/pachl/.gem/ruby/2.4/gems/pkg-config-1.2.8/lib/pkg-config.rb   Thu Jan 11 03:25:51 2018
    +++ /tmp/pkg-config.rb  Thu Jan 11 03:25:55 2018
    @@ -349,6 +349,7 @@
           "/usr/lib/pkgconfig",
           "/usr/libdata/pkgconfig",
           "/usr/X11/lib/pkgconfig",
    +      "/usr/X11R6/lib/pkgconfig",
           "/opt/X11/lib/pkgconfig",
           "/usr/share/pkgconfig",
         ]

What do you think?

Thanks,
pachl

**Comment by kou** [comment]
Can you show the output of `pkg-config --variable pc_path pkg-config`?
We should add `/usr/X11R6/lib/pkgconfig` to the `default_paths`. The output will help us to define where we should put `/usr/X11R6/lib/pkgconfig` to.

**Comment by clintpachl** [comment]
$ pkg-config --variable pc_path pkg-config
    /usr/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/X11R6/lib/pkgconfig:/usr/X11R6/share/pkgconfig

**Comment by kou** [comment]
Thanks. Can you try 1.2.9?

**Comment by clintpachl** [comment]
$ gem install cairo
    Fetching: pkg-config-1.2.9.gem (100%)
    Successfully installed pkg-config-1.2.9
    Fetching: cairo-1.15.11.gem (100%)
    Building native extensions.  This could take a while...
    Successfully installed cairo-1.15.11
    2 gems installed

Perfect! Thanks kou.
